export enum ENV_KEYS {
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_ACCESS_EXPIRATION = 'JWT_ACCESS_EXPIRATION',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION',
  JWT_EMAIL_SECRET = 'JWT_EMAIL_SECRET',
  JWT_EMAIL_EXPIRATION = 'JWT_EMAIL_EXPIRATION',
  PORT = 'PORT',
  SMTP_ENCRYPTION_KEY = 'SMTP_ENCRYPTION_KEY',
  NODE_ENV = 'NODE_ENV',
}
